baseURL = "https://www.mpkato.net/"
languageCode = "en-us"
hasCJKLanguage = true
metaDataFormat = "yaml"
theme = "hugo-bootstrap"
googleAnalytics = "UA-25007161-1"
enableRobotsTXT = true

[params]
  images = ["/images/mpkato.jpg"]

[blackfriday]
   hrefTargetBlank = true

[languages.en]
  languageName = "English"
  title = "Makoto P. Kato"
  copyright = " "
  description = "I'm an associate professor in University of Tsukuba, Japan. My research interests include Information Retrieval, Web Mining, and Machine Learning."

  [[languages.en.menu.main]]
    url = "/research/"
    name = "Research"
    weight = 1
  [[languages.en.menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 2
  [[languages.en.menu.main]]
    url = "/activities/"
    name = "Activities"
    weight = 3

[languages.ja]
  languageName = "日本語"
  title = "加藤 誠 (Makoto P. Kato)"
  copyright = " "
  description = "筑波大学の准教授です．情報検索，Webマイニング，機械学習に興味があります．"

  [[languages.ja.menu.main]]
    url = "/research/"
    name = "研究"
    weight = 1
  [[languages.ja.menu.main]]
    url = "/publications/"
    name = "業績"
    weight = 2
  [[languages.ja.menu.main]]
    url = "/activities/"
    name = "活動"
    weight = 3

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
